core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('base/', views.base, name='base'), 
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
]

core/views.py
from django.shortcuts import render

# Create your views here.

def base(request):
    return render(request, 'core/base.html')

def home(request):
    return render(request, 'core/home.html')

def contact(request):
    return render(request, 'core/contact.html')

core/templates/core/base.html
{% load static %}
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Journee</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Free HTML5 Website Template by GetTemplates.co" />
        <meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
        <meta name="author" content="GetTemplates.co" />
    
        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel="shortcut icon" href="favicon.ico">
    
        <!-- Google Webfonts -->
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,700' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    
        <!-- Animate.css -->
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <!-- Icomoon Icon Fonts-->
        <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
        <!-- Bootstrap  -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <!-- Superfish -->
        <link rel="stylesheet" href="{% static 'css/superfish.css' %}">
        <!-- Magnific Popup -->
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
        <!-- Date Picker -->
        <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
        <!-- CS Select -->
        <link rel="stylesheet" href="{% static 'css/cs-select.css' %}">
        <link rel="stylesheet" href="{% static 'css/cs-skin-border.css' %}">
    
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
        <!-- Modernizr JS -->
        <script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
        <!-- FOR IE9 below -->
        <!--[if lt IE 9]>
        <script src="js/respond.min.js"></script>
        <![endif]-->
    
    </head>
<body>
    <div id="messages">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div id="gtco-wrapper">
        <div id="gtco-page">
            <div id="gtco-header">
                <header id="gtco-header-section">
                <div class="container">
                    <div class="nav-header">
                    <a href="#" class="js-gtco-nav-toggle gtco-nav-toggle"><i></i></a>
                    <h1 id="gtco-logo"><a href="{% url 'core:home' %}">Journee</a></h1>
                    <nav id="gtco-menu-wrap" role="navigation">
                        <ul class="sf-menu" id="gtco-primary-menu">
                        <li><a href="{% url 'core:home' %}">Home</a></li>
                        <li><a href="">booking</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'users:view_profile' %}">Profile</a></li>
                            <li><a href="{% url 'users:logout' %}">Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'users:login' %}">Login</a></li>
                            <li><a href="{% url 'users:register' %}">signUp</a></li>
                        {% endif %}  
                            <li><a href="{% url 'core:contact' %}">Contact</a></li> 
                        {% if logged_out %}
                            <p class="success">You have been logged out.</p>
                        {% endif %}
                        </ul>
                    </nav>
                    </div>
                </div>
                </header>
            </div>
            {% block content %}
            {% endblock %}
        </div>
    </div>


    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- jQuery Easing -->
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Waypoints -->
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <!-- Carousel -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <!-- countTo -->
    <script src="{% static 'js/jquery.countTo.js' %}"></script>
    <!-- Stellar -->
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <!-- Magnific Popup -->
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/magnific-popup-options.js' %}"></script>
    <!-- Datepicker -->
    <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
    <!-- CS Select -->
    <script src="{% static 'js/classie.js' %}"></script>
    <script src="{% static 'js/selectFx.js' %}"></script>
    <!-- Main -->
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE HTML>
<!--
	Aesthetic by gettemplates.co
	Twitter: http://twitter.com/gettemplateco
	URL: http://gettemplates.co
-->
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Journee &mdash; </title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by GetTemplates.co" />
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
	<meta name="author" content="GetTemplates.co" />

<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Themify Icons-->
	<link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

	<!-- Magnific Popup -->
	<link rel="stylesheet"  href="{% static 'css/bootstrap-datepicker.min.css' %}">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

	</head>
	<body>
		
	<div class="gtco-loader"></div>
	
	<div id="page">

	
	<!-- <div class="page-inner"> -->
	
	<header id="gtco-header" class="gtco-cover gtco-cover-sm" role="banner" style="background-image: url(images/NYC.jpg)">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-left">
					<div class="row row-mt-15em">

						<div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp">
							<span class="intro-text-small">Don't be shy</span>
							<h1>Get In Touch</h1>	
						</div>
						
					</div>
					
				</div>
			</div>
		</div>
	</header>
	
	
	<div class="gtco-section border-bottom" style="background: rgb(169, 91, 91); color: white;">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12">
					<div class="col-md-6 animate-box">
					<h3>Get In Touch</h3>
					<form action="#" >
						<div class="row form-group" >
							<div class="col-md-12" >
								<label class="sr-only" for="name">Name</label>
								<input type="text" id="name" class="form-control" placeholder="Your firstname">
							</div>
							
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<label class="sr-only" for="email">Email</label>
								<input type="text" id="email" class="form-control" placeholder="Your email address">
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<label class="sr-only" for="subject">Subject</label>
								<input type="text" id="subject" class="form-control" placeholder="Your subject of this message">
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<label class="sr-only" for="message">Message</label>
								<textarea name="message" id="message" cols="30" rows="10" class="form-control" placeholder="Write us something"></textarea>
							</div>
						</div>
						<div class="form-group">
							<input type="submit" value="Send Message" class="btn btn-primary" style="background: #1f7180;">
						</div>

					</form>		
				</div>
				<div class="col-md-5 col-md-push-1 animate-box" >
					
					<div class="gtco-contact-info">
						<h3>Contact Information</h3>
						<ul>
							<li class="address">198 West 21th Street, <br> Suite 721 New York NY 10016</li>
							<li class="phone"><a href="tel://1234567920">+ 1235 2355 98</a></li>
							<li class="email"><a href="mailto:info@yoursite.com">info@yoursite.com</a></li>
							<li class="url"><a href="http://GetTemplates.co">GetTemplates.co</a></li>
						</ul>
					</div>
				</div>
				</div>
			</div>
		</div>
	</div>

	<footer id="gtco-footer" role="contentinfo" style="background: #1f7180; color: white;">
		<div class="gtco-container">
			<div class="row row-p	b-md">

				<div class="col-md-4">
					<div class="gtco-widget">
						<h3>About Us</h3>
						<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore eos molestias quod sint ipsum possimus temporibus officia iste perspiciatis consectetur in fugiat repudiandae cum. Totam cupiditate nostrum ut neque ab?</p>
					</div>
				</div>

				<div class="col-md-2 col-md-push-1">
					<div class="gtco-widget">
						<h3>Destination</h3>
						<ul class="gtco-footer-links">
							<li><a href="#">Europe</a></li>
							<li><a href="#">Australia</a></li>
							<li><a href="#">Asia</a></li>
							<li><a href="#">Canada</a></li>
							<li><a href="#">Dubai</a></li>
						</ul>
					</div>
				</div>

				<div class="col-md-2 col-md-push-1">
					<div class="gtco-widget">
						<h3>Hotels</h3>
						<ul class="gtco-footer-links">
							<li><a href="#">Luxe Hotel</a></li>
							<li><a href="#">Italy 5 Star hotel</a></li>
							<li><a href="#">Dubai Hotel</a></li>
							<li><a href="#">Deluxe Hotel</a></li>
							<li><a href="#">BoraBora Hotel</a></li>
						</ul>
					</div>
				</div>

				<div class="col-md-3 col-md-push-1">
					<div class="gtco-widget">
						<h3>Get In Touch</h3>
						<ul class="gtco-quick-contact">
							<li><a href="#"><i class="icon-phone"></i> +1 234 567 890</a></li>
							<li><a href="#"><i class="icon-mail2"></i> info@GetTemplates.co</a></li>
							<li><a href="#"><i class="icon-chat"></i> Live Chat</a></li>
						</ul>
					</div>
				</div>

			</div>

			<div class="row copyright">
				<div class="col-md-12">
					<p class="pull-left">
						<small class="block">&copy; 2016 Free HTML5. All Rights Reserved.</small> 
						<small class="block">Designed by <a href="http://GetTemplates.co/" target="_blank">GetTemplates.co</a> Demo Images: <a href="http://unsplash.com/" target="_blank">Unsplash</a></small>
					</p>
					<p class="pull-right">
						<ul class="gtco-social-icons pull-right">
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
						</ul>
					</p>
				</div>
			</div>

		</div>
	</footer>
	<!-- </div> -->

	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>
	
	<script src="{% static 'js/jquery.min.js' %}"></script>

<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>

<script src="{% static 'js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>

<script src="{% static 'js/owl.carousel.min.js' %}"></script>

<script src="{% static 'js/jquery.countTo.js' %}"></script>

<script src="{% static 'js/jquery.stellar.min.js' %}"></script>

<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/magnific-popup-options.js' %}"></script>

<script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>
	{% endblock content %}
	</body>
	
</html>