users/urls.py
from django.urls import path, include
from core import views
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),  
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('', include('core.urls')),
    
]

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout,  update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        
        if user is not None:
            login(request, user)
            messages.success(request, 'Welcome back ' + username + '!')
            return redirect('core:home')  
        else:
            messages.error(request, "Invalid username or password!")

    return render(request, 'users/auth.html')

def logout_view(request):
    logout(request)
    return redirect('core:home')

def register_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password != confirm_password:
            messages.error(request, "Passwords do not match!")
            return redirect('users:register')

        if User.objects.filter(email=email).exists():
            messages.error(request, "Email already exists!")
            return redirect('users:register')

        if User.objects.filter(username=username).exists():
            messages.error(request, "Username already exists!")
            return redirect('users:register')

        user = User.objects.create_user(username=username, email=email, password=password)
        user.save()
        
        '''
        send_mail(
            'Welcome to our site',
            'Thank you for registering on our website.',
            settings.DEFAULT_FROM_EMAIL,
            [email],
            fail_silently=False,
        )
        '''
        messages.success(request, "Registered successfully! Please check your email.")
        return redirect('users:login')

    return render(request, 'users/auth.html')


@login_required
def view_profile(request):
    
    context = {
        'username': request.user.username,
        'email': request.user.email,
    }
    return render(request, 'users/user_profile.html', context)

@login_required
def edit_profile(request):
    if request.method == 'POST':
        
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

        user = request.user
        user.username = username
        user.email = email
        
        if password:
            update_session_auth_hash(request, user)  # Prevents logout after password change
        user.save()

        messages.success(request, 'Your profile has been updated successfully.')
        return redirect('users:view_profile')

    return render(request, 'users/edit_profile.html')

users/templates/users/auth.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE HTML>
<html>
	<head>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Traveler &mdash; journey</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="travel Website " />
		<meta name="keywords" content="travel" />
		<meta name="author" content="travel" />

			<!-- Facebook and Twitter integration -->
		<meta property="og:title" content=""/>
		<meta property="og:image" content=""/>
		<meta property="og:url" content=""/>
		<meta property="og:site_name" content=""/>
		<meta property="og:description" content=""/>
		<meta name="twitter:title" content="" />
		<meta name="twitter:image" content="" />
		<meta name="twitter:url" content="" />
		<meta name="twitter:card" content="" />

		<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
		
		<link rel="stylesheet" href="{% static 'css/animate.css' %}">

		<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">

		<link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">

		<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

		<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

		<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">

		<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" href="{% static 'css/signUp.css' %}">

		<style>
			.message {
				background-color: #f0f0f0;
				padding: 10px;
				border-radius: 5px;
				margin-bottom: 10px;
				position: fixed;
				top: 10px;
				left: 50%;
				transform: translateX(-50%);
				z-index: 1000;
			}
		</style>

	</head>
	<body>
		

		<div id="page">
		<!-- <div class="page-inner"> -->
		<div class="cotn_principal">
			<div class="cont_centrar">
			
			<div class="cont_login">
			<div class="cont_info_log_sign_up">
				<div class="col_md_login">
			<div class="cont_ba_opcitiy">
					
					<h2>LOGIN</h2>  
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p> 
			<button class="btn_login" onclick="change_to_login()">LOGIN</button>
			</div>
			</div>
			<div class="col_md_sign_up">
			<div class="cont_ba_opcitiy">
			<h2>SIGN UP</h2>
        
    
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
			
			<button class="btn_sign_up" onclick="change_to_sign_up()">SIGN UP</button>
			</div>
				</div>
					</div>
			
				
				<div class="cont_back_info">
					<div class="cont_img_back_grey">
					<img src="https://images.unsplash.com/42/U7Fc1sy5SCUDIu4tlJY3_NY_by_PhilippHenzler_philmotion.de.jpg?ixlib=rb-0.3.5&q=50&fm=jpg&crop=entropy&s=7686972873678f32efaf2cd79671673d" alt="" />
					</div>
			
				</div>
					{% for message in messages %}
						<li class="message">{{ message }}</li>
					{% endfor %}
					
			</div>
			<div class="cont_forms" >
				<div class="cont_img_back_">
				<img src="https://images.unsplash.com/42/U7Fc1sy5SCUDIu4tlJY3_NY_by_PhilippHenzler_philmotion.de.jpg?ixlib=rb-0.3.5&q=50&fm=jpg&crop=entropy&s=7686972873678f32efaf2cd79671673d" alt="" />
				</div>
			<div>
				<form class="cont_form_login" method="POST" action="{% url 'users:login' %}">
					{% csrf_token %}
					
					<a href="#" onclick="hidden_login_and_sign_up()" ><i class="material-icons">&#xE5C4;</i></a>
					<h2>LOGIN</h2>
					
					<input type="text" name="username" placeholder="username" required />
					<input type="password" name="password" placeholder="Password" required />
					<button class="btn_login" type="submit" name="login_button" >LOGIN</button>
				</form>
	
			</div>
    
			<div>
				<form class="cont_form_sign_up" method="POST" action="{% url 'users:register' %}">
					{% csrf_token %}
					
					<a href="#" onclick="hidden_login_and_sign_up()"><i class="material-icons">&#xE5C4;</i></a>
					<h2>SIGN UP</h2>
					<input type="text" name="username" id="username" placeholder="username" required />
					
					<input type="text" name="email" id="email" placeholder="email" required />
					
					<input type="password" name="password" id="password" placeholder="password" required /> 
					
					<input type="password" name="confirm_password" id="confirm_password" placeholder="confirm password" required /> 
					<button class="btn_sign_up" type="submit">SIGN UP</button>
					
				</form>
			</div>
			
            
				</div>
			</div>
			</div>
			<script>
            /* ------------------------------------ Click on login and Sign Up to  changue and view the effect
---------------------------------------
*/

const time_to_show_login = 400;
const time_to_hidden_login = 200;

function change_to_login() {
document.querySelector('.cont_forms').className = "cont_forms cont_forms_active_login";  
document.querySelector('.cont_form_login').style.display = "block";
document.querySelector('.cont_form_sign_up').style.opacity = "0";               

setTimeout(function(){  document.querySelector('.cont_form_login').style.opacity = "1"; },time_to_show_login);  

setTimeout(function(){    
document.querySelector('.cont_form_sign_up').style.display = "none";
},time_to_hidden_login);  
}

const time_to_show_sign_up = 100;
const time_to_hidden_sign_up = 400;

function change_to_sign_up(at) {
document.querySelector('.cont_forms').className = "cont_forms cont_forms_active_sign_up";
document.querySelector('.cont_form_sign_up').style.display = "block";
document.querySelector('.cont_form_login').style.opacity = "0";

setTimeout(function(){  document.querySelector('.cont_form_sign_up').style.opacity = "1";
},time_to_show_sign_up);  

setTimeout(function(){   document.querySelector('.cont_form_login').style.display = "none";
},time_to_hidden_sign_up);  


}    

const time_to_hidden_all = 500;

function hidden_login_and_sign_up() {

document.querySelector('.cont_forms').className = "cont_forms";  
document.querySelector('.cont_form_sign_up').style.opacity = "0";               
document.querySelector('.cont_form_login').style.opacity = "0"; 

setTimeout(function(){
document.querySelector('.cont_form_sign_up').style.display = "none";
document.querySelector('.cont_form_login').style.display = "none";
},time_to_hidden_all);  
}
setTimeout(function() {
            var messages = document.getElementById('messages');
            if (messages) {
                messages.style.display = 'none';
            }
        }, 5000);

        </script>
    <!-- jQuery -->
<script src="{% static 'js/jquery.min.js' %}"></script>

<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>

<script src="{% static 'js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>

<script src="{% static 'js/owl.carousel.min.js' %}"></script>

<script src="{% static 'js/jquery.countTo.js' %}"></script>

<script src="{% static 'js/jquery.stellar.min.js' %}"></script>

<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/magnific-popup-options.js' %}"></script>

<script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>

	{% endblock content %}
	</body>
</html>

users/templates/users/edit_profile.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Traveler &mdash; journey</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="travel Website " />
	<meta name="keywords" content="travel" />
	<meta name="author" content="travel" />

	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
		
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">

	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">

	<link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">

	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

	<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">

	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

	<link rel="stylesheet" href="{% static 'css/editprofile.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->
</head>
<body>
<div id="page">
    <div class="form-container">
	<h2>Edit Profile</h2>
    <form id="editProfileForm" method="POST" action="{% url 'users:edit_profile' %}">
		{% csrf_token %}
        <label for="user_name">Name:</label>
        <input type="text" id="username" name="username" value="{{ user.username }}">

        <label for="number_of_plans">Number of Plans:</label>
        <input type="number" id="number_of_plans" name="number_of_plans" value="">

        <label for="email">Email:</label>
        <input type="email" id="email" name="email" placeholder="Enter email address"value="{{ user.email }}">
        
        <label for="password">Change Password:</label>
        <input type="password" id="password" name="password" placeholder="Enter password">
        

        <button type="submit">Save Changes</button>
        <button type="button" class="cancel-btn" id="cancelButton">Cancel</button>
    </form>
    </div>
	
<script>
	document.getElementById("cancelButton").onclick = function() {
		window.location.href = "{% url 'users:view_profile' %}";
	};
</script>
{% endblock content %}
</body>

</html>

users/templates/users/user_profile.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Traveler &mdash; journey</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="travel Website " />
	<meta name="keywords" content="travel" />
	<meta name="author" content="travel" />

	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
	
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">

  <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">

  <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">

  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/userform.css' %}">

  <script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->
  <title>User profile</title>
</head>
<body>
  <div class="gtco-container">
  <div id="page">
  <div class="card">
    <div class="card_background_img"></div>
    <div class="card_profile_img"></div>
    <div class="user_details">
      <h1>{{ username }}</h1>
      <p>Email: {{ email }}</p>
      <form method="get" action="{% url 'users:edit_profile' %}">
        {% csrf_token %}
        <button class="edit-profile-btn" id="editProfileBtn" >Edit Profile</button>
      </form>
    </div>
  </div>
  <script>
    document.getElementById("editProfileBtn").addEventListener("click", function() {
      window.location.href = "editprofile.html";
    });

// Load and display data from local storage
window.onload = function() {
  const backgroundImg = localStorage.getItem('backgroundImg');
  const profileImg = localStorage.getItem('profileImg');
  const userName = localStorage.getItem('userName');
  const numberOfPlans = localStorage.getItem('numberOfPlans');
  const email = localStorage.getItem('email');

  if (backgroundImg) {
    document.querySelector('.card_background_img').style.backgroundImage = `url(${backgroundImg})`;
  }

  if (profileImg) {
    document.querySelector('.card_profile_img').style.backgroundImage = `url(${profileImg})`;
  }

  if (userName) {
    document.querySelector('.user_details h1').textContent = userName;
  }

  if (numberOfPlans) {
    document.querySelector('.user_details p:nth-of-type(1)').textContent = `Number of plans: ${numberOfPlans}`;
  }

  if (email) {
    document.querySelector('.user_details p:nth-of-type(2)').textContent = `Email: ${email}`;
  }
};
  </script>
{% endblock content %}
</body>
</html>